#stage 1-frontend
FROM node:20-alpine as frontend-build


WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . /app
RUN npm run build

#stage 2-fullstack


FROM node:20-alpine

WORKDIR /app
COPY package*.json /app
RUN npm install
COPY . /app

COPY --from=frontend-build /app/dist /app/public
EXPOSE 3000
CMD ["node", "server.js"]